[package]
name = "diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
# Libs in project
span = { path = "../span" }
ir = { path = "../ir" }
op = { path = "../op" }
token = { path = "../token" }

# Extern crates
fxhash = "0.2.1"