[package]
name = "parser"
version = "0.1.0"
edition = "2021"



[dependencies]
enum-iterator = "2.1.0"
array-init = "2.1.0"
lexer = { path = "../lexer" }
token = { path = "../token" }
op = { path = "../op" }
expr_builder = { path = "../expr_builder" }
ast = { path = "../ast" }
ast_state = { path = "../ast_state" }
span = { path = "../span" }
precedence = { path = "../precedence" }