[package]
name = "resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
# Libs in project
ast = { path = "../ast" }
ir = { path = "../ir" }
error = { path = "../error" }
span = { path = "../span" }
parser = { path = "../parser" }

# Extern crates
bumpalo = "3.1.16"
fxhash = "0.2.1"