[package]
name = "expr_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
op = { path = "../op" }
precedence = { path = "../precedence" }
ast_state = { path = "../ast_state" }