[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
data_structures = { path = "../data_structures" }
op = { path = "../op" }
span = { path = "../span" }
token = { path = "../token" }

bumpalo = "3.1.16"
fxhash = "0.2.1"
derive-new = "0.7.0"
enum-iterator = "2.1.0"