[package]
name = "icfg"
version = "0.1.0"
edition = "2021"

[dependencies]
# Libs in project
op = { path = "../op" }
ir = { path = "../ir" }
span = { path = "../span" }
data_structures = { path = "../data_structures" }

# Extern crate
derive-new = "0.7.0"